const colors = {
  light: {
    text: "#0A0A0A",
    tint: "#0A0A0A",
    background: "#FFFFFF",
    foreground: "#0A0A0A",
    card: "#F7F7F7",
    cardForeground: "#0A0A0A",
    primary: "#0A0A0A",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F0",
    secondaryForeground: "#444444",
    muted: "#F0F0F0",
    mutedForeground: "#666666",
    accent: "#0A0A0A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5E5",
    input: "#F5F5F5",
    highlight: "#EBEBEB",
    highlightForeground: "#0A0A0A",
    neonPurple: "#7C3AED",
    neonCyan: "#06B6D4",
    neonPink: "#EC4899",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FFFFFF",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#111111",
    cardForeground: "#FFFFFF",
    primary: "#FFFFFF",
    primaryForeground: "#0A0A0A",
    secondary: "#1A1A1A",
    secondaryForeground: "#AAAAAA",
    muted: "#1A1A1A",
    mutedForeground: "#777777",
    accent: "#FFFFFF",
    accentForeground: "#0A0A0A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#232323",
    input: "#141414",
    highlight: "#222222",
    highlightForeground: "#FFFFFF",
    neonPurple: "#8B5CF6",
    neonCyan: "#22D3EE",
    neonPink: "#F472B6",
  },
  radius: 12,
};

export default colors;
